#!/usr/bin/env python
"""Build the grid-anchor shortest-path distance/time matrix.

This script uses the projected ``road.graphml`` and ``anchors.csv`` generated by
``preprocess_osm.py``. Matrix row/column ids are the compact ``grid_id`` values,
which are also used by normalized ``orders.csv`` and ``vehicles.csv``.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import networkx as nx
import numpy as np
import pandas as pd


def _require_osmnx() -> Any:
    try:
        import osmnx as ox  # type: ignore
    except ImportError as exc:  # pragma: no cover - optional dependency path
        raise SystemExit(
            "OSMnx is required for shortest-path matrix construction. Install it with:\n"
            "    pip install -r requirements-geospatial.txt"
        ) from exc
    return ox


def _get_ox_fn(ox: Any, name: str) -> Any:
    candidates = {
        "load_graphml": ["load_graphml", "io.load_graphml"],
    }[name]
    for dotted in candidates:
        try:
            cur = ox
            for part in dotted.split("."):
                cur = getattr(cur, part)
            return cur
        except AttributeError:
            continue
    raise AttributeError(f"Cannot find OSMnx function {name}")


def _node_key(graph: nx.Graph, raw: Any) -> Any:
    # GraphML may restore OSM node ids as strings. Try both forms.
    if raw in graph:
        return raw
    raw_str = str(raw)
    if raw_str in graph:
        return raw_str
    try:
        raw_int = int(raw)
        if raw_int in graph:
            return raw_int
    except Exception:
        pass
    raise KeyError(f"Anchor node {raw!r} not found in graph")


def _to_simple_digraph(graph: nx.MultiDiGraph, weight: str) -> nx.DiGraph:
    simple = nx.DiGraph()
    for u, v, data in graph.edges(data=True):
        w = float(data.get(weight, np.inf))
        if not np.isfinite(w):
            continue
        if simple.has_edge(u, v):
            if w < simple[u][v][weight]:
                simple[u][v][weight] = w
        else:
            simple.add_edge(u, v, **{weight: w})
    return simple


def _fill_matrix(graph: nx.DiGraph, anchor_nodes: list[Any], weight: str, dtype: str) -> np.ndarray:
    n = len(anchor_nodes)
    matrix = np.full((n, n), np.inf, dtype=dtype)
    index = {node: i for i, node in enumerate(anchor_nodes)}
    for i, source in enumerate(anchor_nodes):
        lengths = nx.single_source_dijkstra_path_length(graph, source, weight=weight)
        matrix[i, i] = 0.0
        for node, value in lengths.items():
            j = index.get(node)
            if j is not None:
                matrix[i, j] = float(value)
        if (i + 1) % 50 == 0 or i + 1 == n:
            print(f"  {weight}: {i + 1}/{n} sources processed")
    return matrix


def main() -> None:
    parser = argparse.ArgumentParser(description="Build all-pairs shortest-path matrices between grid anchors.")
    parser.add_argument("--city-dir", type=Path, required=True, help="Directory with road.graphml and anchors.csv")
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--dtype", choices=["float32", "float64"], default="float32")
    args = parser.parse_args()

    ox = _require_osmnx()
    load_graphml = _get_ox_fn(ox, "load_graphml")

    graph_path = args.city_dir / "road.graphml"
    anchors_path = args.city_dir / "anchors.csv"
    if not graph_path.exists() or not anchors_path.exists():
        raise FileNotFoundError("Expected road.graphml and anchors.csv in the city directory")

    print("[1/4] loading graph and anchors")
    graph = load_graphml(graph_path)
    anchors = pd.read_csv(anchors_path).sort_values("grid_id")
    anchor_nodes = [_node_key(graph, node) for node in anchors["anchor_node"].tolist()]

    print("[2/4] building length matrix")
    length_graph = _to_simple_digraph(graph, "length")
    distance = _fill_matrix(length_graph, anchor_nodes, "length", args.dtype)

    print("[3/4] building travel-time matrix")
    time_graph = _to_simple_digraph(graph, "travel_time")
    if time_graph.number_of_edges() == 0:
        raise ValueError("Graph has no travel_time edge attributes. Re-run preprocess_osm.py.")
    travel_time = _fill_matrix(time_graph, anchor_nodes, "travel_time", args.dtype)

    coords = anchors[["centroid_x", "centroid_y"]].to_numpy(dtype=args.dtype)
    out = args.out or (args.city_dir / "grid_matrix.npz")
    out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(out, distance=distance, time=travel_time, coords=coords)

    metadata_path = args.city_dir / "metadata.json"
    if metadata_path.exists():
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    else:
        metadata = {}
    metadata.update(
        {
            "matrix_file": str(out.name),
            "matrix_nodes": int(len(anchor_nodes)),
            "matrix_dtype": args.dtype,
            "distance_unit": "meter",
            "time_unit": "second",
        }
    )
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print("[4/4] done")
    print(f"saved: {out} with shape {distance.shape}")


if __name__ == "__main__":
    main()
